<?php

/**
 * Main block for module
 *
 * @category   Rejoiner
 * @package    Rejoiner_Acr
 */
class Rejoiner_Acr_Block_Snippets extends Rejoiner_Acr_Block_Base
{

    const XML_PATH_REJOINER_TRACK_PRICE_WITH_TAX = 'checkout/rejoiner_acr/price_with_tax';

    /**
     * @return array
     */
    public function getCartData()
    {
        $cartData = array();
        if ($quote = $this->_getQuote()) {
            if ($this->getTrackPriceWithTax()) {
                $total = $this->_getQuote()->getGrandTotal();
            } else {
                $total = $this->_getQuote()->getSubtotal();
            }

            $cartData = array(
                'total_items_count' => intval($this->_getQuote()->getItemsQty()),
                'cart_value'        => $this->_convertPriceToCents($total),
                'return_url'        => (string) Mage::helper('rejoiner_acr')->getRestoreUrl(),
            );
            if (Mage::getStoreConfig('checkout/rejoiner_acr/coupon_code')) {
                $cartData['promo'] = (string) $this->_generateCouponCode();
            }
        }
        return $cartData;
    }

    /**
     * @return string
     */
    protected function _generateCouponCode()
    {
        /** @var Mage_Checkout_Helper_Cart $cartHelper */
        $cartHelper = Mage::helper('checkout/cart');
        /** @var Mage_Sales_Model_Quote $quote */
        $quote      = $cartHelper->getCart()->getQuote();
        $couponCode = $quote->getPromo();
        $ruleId     = Mage::getStoreConfig('checkout/rejoiner_acr/salesrule_model');
        /** @var Mage_SalesRule_Model_Rule $ruleItem */
        $ruleItem   = Mage::getModel('salesrule/rule')
            ->getCollection()
            ->addFieldToFilter('rule_id', array('eq' => $ruleId))
            ->getFirstItem();

        if ($ruleItem->getUseAutoGeneration() && !$couponCode) {
            /** @var Mage_SalesRule_Model_Coupon_Codegenerator $codeGenerator */
            $codeGenerator = Mage::getModel('salesrule/coupon_codegenerator');
            $couponCode = $codeGenerator->generateCode();

            /** @var Mage_SalesRule_Model_Coupon $coupon */
            $coupon = Mage::getModel('salesrule/coupon');
            $coupon->setRuleId($ruleId)
                ->setCode($couponCode)
                ->setUsageLimit(1)
                ->setType(Mage_SalesRule_Helper_Coupon::COUPON_TYPE_SPECIFIC_AUTOGENERATED)
                ->save();

            $cartHelper->getCart()
                ->getQuote()
                ->setPromo(strlen($couponCode) ? $couponCode : '')
                ->save();
        }
        return $couponCode;
    }

    /**
     * @return Mage_Sales_Model_Quote
     */
    protected function _getQuote()
    {
        return Mage::getSingleton('checkout/session')->getQuote();
    }

    /**
     * @param $price
     * @return float
     */
    protected function _convertPriceToCents($price) {
        return round($price*100);
    }

    /**
     * @return bool
     */
    protected function getTrackPriceWithTax()
    {
        return Mage::getStoreConfig(self::XML_PATH_REJOINER_TRACK_PRICE_WITH_TAX);
    }
}
